title: Clarkezone Dev Blog
description: code and nerdy
author: James Clarke
github: https://github.com/clarkezone
about: By day I work on the Windows engineering team.  By night I enjoy learning new things.
disqus_shortname: clarkezone
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar2.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/clarkezone"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/clarkezone"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/clarkezone"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://clarkezone.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
