title: Clarkezone Dev Blog
description: code and nerdy
author: James Clarke
github: https://github.com/clarkezone
about: By day I work at Microsoft in Redmond, WA.  By night I enjoy learning new tools and technologies.  This blog will cover both MSFT and non-MSFT related topics.  All opinions expressed here are mine own.
disqus_shortname: clarkezone-github-io
google_analytics: UA-129276880-1
avatar_url: /static/img/avatar2.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/Clarkezone"
    - icon: fa-twitter
      link: "https://twitter.com/clarkezone"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/clarkezone"
    - icon: fa-squarespace
      link: "https://clarkezone.io"
    - icon: fa-github
      link: "https://github.com/clarkezone"

share:
  twitter_username: clarkezone
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://clarkezone.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
